namespace PM.Guillem.AIOpenSDK.Core;

using System.Reflection;

/// <summary>
/// Structured / JSON output binding on "AIOS Chat Request".
/// </summary>
codeunit 87425 "AIOS Chat Output"
{
    Access = Public;

    /// <summary>
    /// Binds flat JSON fields onto RecRef. GenerateText(Model, Request, RecRef) rebinds to the RecRef passed there.
    /// Prefer SetOutput with a JSON Schema for nested shapes.
    /// </summary>
    procedure SetOutput(var Request: Record "AIOS Chat Request"; RecRef: RecordRef)
    var
        JsonBinder: Codeunit "AIOS Json Binder";
    begin
        if RecRef.Number() = 0 then
            Error(OutputRecordMissingErr);

        ClearOutput(Request);
        Request."Has Output" := true;
        Request."Json Mode" := true;
        SetOutputInstruction(Request, JsonBinder.BuildSchemaHint(RecRef));
    end;

    /// <summary>
    /// Sets the output mode from a schema document. Object/Array/Choice/Json enable JSON mode and add a hint to the effective system message.
    /// Text disables JSON mode and does not append a hint (same as omitting SetOutput).
    /// </summary>
    procedure SetOutput(var Request: Record "AIOS Chat Request"; SchemaText: Text)
    var
        SchemaCodeunit: Codeunit "AIOS Schema";
        SchemaObj: JsonObject;
        OutStream: OutStream;
        Hint: Text;
        IsText: Boolean;
        IsJson: Boolean;
    begin
        if DelChr(SchemaText, '<>', ' ') = '' then
            Error(OutputSchemaMissingErr);

        ClearOutput(Request);
        Request."Output Schema".CreateOutStream(OutStream, TextEncoding::UTF8);
        OutStream.WriteText(SchemaText);
        Request."Has Output Schema" := true;

        IsText := false;
        IsJson := false;
        if SchemaObj.ReadFrom(SchemaText) then begin
            IsText := SchemaCodeunit.IsTextSchema(SchemaObj);
            IsJson := SchemaCodeunit.IsJsonSchema(SchemaObj);
        end;
        Request."Json Mode" := not IsText;

        if IsText then
            Hint := ''
        else
            if IsJson then
                Hint := JsonModeInstructionTxt
            else
                Hint := StrSubstNo(OutputSchemaHintTxt, SchemaText);

        SetOutputInstruction(Request, Hint);
    end;

    /// <summary>
    /// Sets structured output from a schema JsonObject (serialized via "AIOS Schema".ToText).
    /// </summary>
    procedure SetOutput(var Request: Record "AIOS Chat Request"; Schema: JsonObject)
    var
        SchemaCodeunit: Codeunit "AIOS Schema";
    begin
        SetOutput(Request, SchemaCodeunit.ToText(Schema));
    end;

    /// <summary>
    /// Returns true when the request is bound for RecRef structured output.
    /// </summary>
    procedure HasOutput(var Request: Record "AIOS Chat Request"): Boolean
    begin
        exit(Request."Has Output");
    end;

    /// <summary>
    /// Returns true when the request has an output JSON Schema.
    /// </summary>
    procedure HasOutputSchema(var Request: Record "AIOS Chat Request"): Boolean
    begin
        exit(Request."Has Output Schema");
    end;

    /// <summary>
    /// Returns the output JSON Schema text stored on the request.
    /// </summary>
    procedure GetOutputSchema(var Request: Record "AIOS Chat Request"): Text
    var
        TypeHelper: Codeunit "Type Helper";
        InStream: InStream;
    begin
        if not Request."Output Schema".HasValue then
            exit('');
        Request."Output Schema".CreateInStream(InStream, TextEncoding::UTF8);
        exit(TypeHelper.ReadAsTextWithSeparator(InStream, TypeHelper.LFSeparator()));
    end;

    /// <summary>
    /// Clears RecRef/schema output binding, disables JSON mode and drops the generated output instruction.
    /// The system message set by the caller is not changed.
    /// </summary>
    procedure ClearOutput(var Request: Record "AIOS Chat Request")
    begin
        Request."Has Output" := false;
        Clear(Request."Output Schema");
        Request."Has Output Schema" := false;
        Request."Json Mode" := false;
        Clear(Request."Output Instruction");
    end;

    /// <summary>
    /// Returns the output instruction generated by SetOutput. Added to the effective system message, never stored in it.
    /// </summary>
    internal procedure GetOutputInstruction(var Request: Record "AIOS Chat Request"): Text
    var
        TypeHelper: Codeunit "Type Helper";
        InStream: InStream;
    begin
        if not Request."Output Instruction".HasValue then
            exit('');
        Request."Output Instruction".CreateInStream(InStream, TextEncoding::UTF8);
        exit(TypeHelper.ReadAsTextWithSeparator(InStream, TypeHelper.LFSeparator()));
    end;

    local procedure SetOutputInstruction(var Request: Record "AIOS Chat Request"; Value: Text)
    var
        OutStream: OutStream;
    begin
        Clear(Request."Output Instruction");
        if Value = '' then
            exit;
        Request."Output Instruction".CreateOutStream(OutStream, TextEncoding::UTF8);
        OutStream.WriteText(Value);
    end;

    var
        OutputRecordMissingErr: Label 'Structured output requires an open record.';
        OutputSchemaMissingErr: Label 'Output schema text cannot be empty.';
        OutputSchemaHintTxt: Label 'Respond with JSON only (no markdown) that conforms to this JSON Schema: %1', Comment = '%1 = JSON Schema';
        JsonModeInstructionTxt: Label 'Respond with valid JSON only, no markdown fences.';
}
